version: '3.8'

services:
  nakup-vstopnic-service:
    build: .
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: vaje
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
