version: '3.8'

services:
  users-service:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    networks:
      - backend-network
    container_name: users-service

  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend-network

volumes:
  mongodb_data_container:

networks:
  backend-network:
    external: true
